/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>


int main(void)
{
	//AHb2ENR ; l'adresse 0x4002104c sur 32 bits
	// il faut l'adresse de meme type que ponteur pour éviter les erreurs
	//le pointeur contient cette adress de AHB2ENR

	uint32_t *PointeurClock = (uint32_t*)0x4002104C;

	//on veut mettre GPIOB à 1 , on utilise shift register

    *PointeurClock  |= (1<<1);

    // configuration du pin PB14 du led interne en mode output
    //l'adresse de gpioB : 0x4800 0400

    uint32_t *PModerReg =(uint32_t*) 0x48000400;
    //Moder est le registre 14 en GIPOB  d'offset 0x00 et contient deux cases 28 et 29
    *PModerReg |= (1<<28);
    *PModerReg &= ~(1<<29);

// configuration write à travers

	uint32_t *POder= (uint32_t*)0x48000414;
    *POder  |= (1<<14);



    /* Loop forever */
	for();
}
